services:
  front:
    build: ./docker/front
    tty: true
    stdin_open: true
    volumes:
      - ./front:/app
      - ./docker/front/entrypoint.sh:/entrypoint.sh
      - ./docker/front/command.sh:/command.sh
      - node_modules:/app/node_modules
    ports:
      - ${REACT_PORT:-5173}:5173
      - ${STORYBOOK_PORT:-6006}:6006
    command: /command.sh

volumes:
  node_modules:
